version: '3.7'
services:
  rainbow-notes-admin:
    build:
      context: ./bot
    environment:
      - TITLE=Admin Bot for Rainbow Notes
      - PORT=8192
      - URL_CHECK_REGEX=^https?://.{1,256}$
      # default `SITE` would be `http://web`
      # please note that `SITE` will be set to the actual, publicly accessible domain
      - SITE=${SITE}
      # format: ^csawctf{[a-f0-9]{10}}$
      - FLAG=${FLAG}
    init: true
    security_opt:
      - seccomp=chrome.json
    ports:
      - "8192:8192"
    networks:
      - rainbownet
      - ctfnet
  rainbow-notes:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "8763:80"
    networks:
      - rainbownet
      - ctfnet

networks:
  rainbownet:
    name: rainbownet
    driver: bridge
  ctfnet:
    external: true
